---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - stable
    - tip
  env:
    global:
      - GO15VENDOREXPERIMENT=1
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - go build -v
    - go vet $(go list ./... | grep -v vendor)
    - staticcheck $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - go test $(go list ./... | grep -v vendor)
    - make release
  deploy:
    provider: releases
    api_key:
      secure: "RNy7v4UfgTI/ivbCFo2k3vA8n7JykYkdcsnmKVT5X2y9HyyyoFsZ68YutaWYqr9y3SrK642SiIE7pa/eoSDp5YsPpSmNn5Rq+/oxNghxRTHBh6dqduPuzfXo9De7cblgww7B1Kh4q2HYaE1Un8RVrKIhXClrqtkGbZiylJxsZegG0snJgVuTo7fbnEGCC/Nulxa01dqkXL9NQ9s9Mo8oyz+nhCRwfJuQ7jCl1hI2dS5XvHoGgg/yu6wbatbkAWxlC2WLs7w/X8o13+Oa1hgpmsVKWvgnOIZvd9gEU2diVrvnpmCylr0ctScWA51XmQh2xsDLEpE2Cz0iLotM31Gq71L93Hp9a3E7VfuzUgrr2NXZBvxZw6PYN5voCIEIEwwNFVHC6OThVgV3a8zDK+jjDLy+X9ggyZmQ5+rjBXaEIfh135skDytKc5AJC+nVMH/3dfrE+r6hgLFSyrnePVqci3veiCUe7tUFiPkoMp4q2Za4se4EEzk3aymQKef8JGyBvzzMZWkP4iUMkpqRNEXtCu9cJKnei5aZHz+KDzdDBh59jPcPH2rhM4NzvyPwgQx0tSJ0RiOTYAmyP/YkRcOuJBhMh8Rwdy2EdtFaT+N5jFIqa7gdYSzXJjMhea1gvMh7wjK0N2Ay5hjti/S8FHj0H9USYcucM1+7O+Cv0OrnUKE="
    file:
      - cross/cliaoke-linux-amd64.md5
      - cross/cliaoke-windows-386.sha256
      - cross/cliaoke-linux-arm
      - cross/cliaoke-darwin-amd64.md5
      - cross/cliaoke-darwin-amd64
      - cross/cliaoke-solaris-amd64.md5
      - cross/cliaoke-linux-arm64.sha256
      - cross/cliaoke-linux-arm.sha256
      - cross/cliaoke-linux-386.sha256
      - cross/cliaoke-darwin-386.md5
      - cross/cliaoke-windows-386.md5
      - cross/cliaoke-freebsd-amd64.md5
      - cross/cliaoke-linux-arm64.md5
      - cross/cliaoke-linux-arm64
      - cross/cliaoke-freebsd-amd64.sha256
      - cross/cliaoke-freebsd-386.md5
      - cross/cliaoke-linux-amd64.sha256
      - cross/cliaoke-linux-386.md5
      - cross/cliaoke-freebsd-386
      - cross/cliaoke-solaris-amd64.sha256
      - cross/cliaoke-windows-amd64
      - cross/cliaoke-windows-amd64.md5
      - cross/cliaoke-windows-amd64.sha256
      - cross/cliaoke-linux-arm.md5
      - cross/cliaoke-darwin-386.sha256
      - cross/cliaoke-darwin-amd64.sha256
      - cross/cliaoke-windows-386
      - cross/cliaoke-solaris-amd64
      - cross/cliaoke-darwin-386
      - cross/cliaoke-linux-386
      - cross/cliaoke-freebsd-amd64
      - cross/cliaoke-freebsd-386.sha256
      - cross/cliaoke-linux-amd64
    skip_cleanup: true
    on:
      go: stable
      tags: true
